module.exports = {
    content: [
      "./src/**/*.{html,js,ts,jsx,tsx}",
      "app/**/*.{ts,tsx}",
      "components/**/*.{ts,tsx}",
    ],
    theme: {
      extend: {
        colors: {
          "colors-app-background": "var(--colors-app-background)",
          "colors-app-border": "var(--colors-app-border)",
          "colors-app-card-foreground": "var(--colors-app-card-foreground)",
          "colors-app-foreground": "var(--colors-app-foreground)",
          "colors-app-muted-foreground": "var(--colors-app-muted-foreground)",
          "colors-foreground-foreground-20":
            "var(--colors-foreground-foreground-20)",
          "colors-foreground-foreground-5":
            "var(--colors-foreground-foreground-5)",
          "colors-white-white": "var(--colors-white-white)",
          "colors-zinc-500": "var(--colors-zinc-500)",
          "colors-zinc-950": "var(--colors-zinc-950)",
          "colors-zinc-950-10": "var(--colors-zinc-950-10)",
          "colors-zinc-950-20": "var(--colors-zinc-950-20)",
          "colors-zinc-950-5": "var(--colors-zinc-950-5)",
          neutrallightlightest: "var(--neutrallightlightest)",
          "variable-collection-error-1": "var(--variable-collection-error-1)",
          "variable-collection-error-2": "var(--variable-collection-error-2)",
          "variable-collection-error-3": "var(--variable-collection-error-3)",
          "variable-collection-grey-0-white":
            "var(--variable-collection-grey-0-white)",
          "variable-collection-grey-1": "var(--variable-collection-grey-1)",
          "variable-collection-grey-2": "var(--variable-collection-grey-2)",
          "variable-collection-grey-3": "var(--variable-collection-grey-3)",
          "variable-collection-grey-4": "var(--variable-collection-grey-4)",
          "variable-collection-grey-5": "var(--variable-collection-grey-5)",
          "variable-collection-grey-6": "var(--variable-collection-grey-6)",
          "variable-collection-grey-7": "var(--variable-collection-grey-7)",
          "variable-collection-grey-8": "var(--variable-collection-grey-8)",
          "variable-collection-grey-9-black":
            "var(--variable-collection-grey-9-black)",
          "variable-collection-sand-1": "var(--variable-collection-sand-1)",
          "variable-collection-sand-2": "var(--variable-collection-sand-2)",
          "variable-collection-sand-3": "var(--variable-collection-sand-3)",
          "variable-collection-sand-4": "var(--variable-collection-sand-4)",
          "variable-collection-sand-5": "var(--variable-collection-sand-5)",
          "variable-collection-sand-6": "var(--variable-collection-sand-6)",
          "variable-collection-sand-7": "var(--variable-collection-sand-7)",
          "variable-collection-success-1": "var(--variable-collection-success-1)",
          "variable-collection-success-2": "var(--variable-collection-success-2)",
          "variable-collection-success-3": "var(--variable-collection-success-3)",
          "variable-collection-warning-1": "var(--variable-collection-warning-1)",
          "variable-collection-warning-2": "var(--variable-collection-warning-2)",
          "variable-collection-warning-3": "var(--variable-collection-warning-3)",
          border: "hsl(var(--border))",
          input: "hsl(var(--input))",
          ring: "hsl(var(--ring))",
          background: "hsl(var(--background))",
          foreground: "hsl(var(--foreground))",
          primary: {
            DEFAULT: "hsl(var(--primary))",
            foreground: "hsl(var(--primary-foreground))",
          },
          secondary: {
            DEFAULT: "hsl(var(--secondary))",
            foreground: "hsl(var(--secondary-foreground))",
          },
          destructive: {
            DEFAULT: "hsl(var(--destructive))",
            foreground: "hsl(var(--destructive-foreground))",
          },
          muted: {
            DEFAULT: "hsl(var(--muted))",
            foreground: "hsl(var(--muted-foreground))",
          },
          accent: {
            DEFAULT: "hsl(var(--accent))",
            foreground: "hsl(var(--accent-foreground))",
          },
          popover: {
            DEFAULT: "hsl(var(--popover))",
            foreground: "hsl(var(--popover-foreground))",
          },
          card: {
            DEFAULT: "hsl(var(--card))",
            foreground: "hsl(var(--card-foreground))",
          },
        },
        fontFamily: {
          "action-l": "var(--action-l-font-family)",
          "action-m": "var(--action-m-font-family)",
          "action-s": "var(--action-s-font-family)",
          "body-l": "var(--body-l-font-family)",
          "body-m": "var(--body-m-font-family)",
          "body-s": "var(--body-s-font-family)",
          "body-XL": "var(--body-XL-font-family)",
          "body-XS": "var(--body-XS-font-family)",
          "caption-m": "var(--caption-m-font-family)",
          "heading-h1": "var(--heading-h1-font-family)",
          "heading-h2": "var(--heading-h2-font-family)",
          "heading-h3": "var(--heading-h3-font-family)",
          "heading-h4": "var(--heading-h4-font-family)",
          "heading-h5": "var(--heading-h5-font-family)",
          "text-2xl-font-semibold": "var(--text-2xl-font-semibold-font-family)",
          "text-5xl-font-semibold": "var(--text-5xl-font-semibold-font-family)",
          "text-base-font-medium": "var(--text-base-font-medium-font-family)",
          "text-base-font-normal": "var(--text-base-font-normal-font-family)",
          "text-sm-font-medium": "var(--text-sm-font-medium-font-family)",
          "text-sm-font-normal": "var(--text-sm-font-normal-font-family)",
          "text-sm-font-semibold": "var(--text-sm-font-semibold-font-family)",
          "text-xl-font-medium": "var(--text-xl-font-medium-font-family)",
          "text-xs-font-normal": "var(--text-xs-font-normal-font-family)",
          sans: [
            "ui-sans-serif",
            "system-ui",
            "sans-serif",
            '"Apple Color Emoji"',
            '"Segoe UI Emoji"',
            '"Segoe UI Symbol"',
            '"Noto Color Emoji"',
          ],
        },
        boxShadow: {
          "box-shadow-shadow-2xl": "var(--box-shadow-shadow-2xl)",
          shimmer: "var(--shimmer)",
        },
        borderRadius: {
          lg: "var(--radius)",
          md: "calc(var(--radius) - 2px)",
          sm: "calc(var(--radius) - 4px)",
        },
        keyframes: {
          "accordion-down": {
            from: { height: "0" },
            to: { height: "var(--radix-accordion-content-height)" },
          },
          "accordion-up": {
            from: { height: "var(--radix-accordion-content-height)" },
            to: { height: "0" },
          },
        },
        animation: {
          "accordion-down": "accordion-down 0.2s ease-out",
          "accordion-up": "accordion-up 0.2s ease-out",
        },
      },
      container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    },
    plugins: [],
    darkMode: ["class"],
  };

  